version: '3.8'

services:
  minecraft-monitor:
    container_name: minecraft-monitor
    image: cachamber/minecraft-monitor
    build: 
      context: .
      tags:
        - "cachamber/minecraft-monitor:latest"
    ports:
      - "3001:3001"
    volumes:
      - ./src/config.json:/app/src/config.json
      - ./wallpapers:/app/wallpapers
      - player-data:/app/data
    environment:
      - NODE_ENV=production
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    restart: unless-stopped
volumes:
  player-data:
